package cn.itcast.mapper;

import com.leyou.pojo.Brand;
import com.leyou.pojo.BrandExample;
import com.leyou.pojo.CategoryBrandKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Mon Aug 24 12:01:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Mon Aug 24 12:01:01 CST 2020
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Mon Aug 24 12:01:01 CST 2020
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Mon Aug 24 12:01:01 CST 2020
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Mon Aug 24 12:01:01 CST 2020
     */
    Brand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Mon Aug 24 12:01:01 CST 2020
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbggenerated Mon Aug 24 12:01:01 CST 2020
     */
    int updateByPrimaryKey(Brand record);

    Brand  select(Brand brand);


    @Select("select tb_brand.* from tb_category_brand left join tb_brand on tb_category_brand.brand_id = tb_brand.id where tb_category_brand.category_id=#{id} ")
    List<Brand> queryByCategoryId(@Param("id") Long id);

}