package cn.itcast.mapper;

import com.leyou.pojo.Category;
import com.leyou.pojo.CategoryBrandKey;

import java.util.List;

public interface CategoryBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbggenerated Wed Aug 26 13:00:16 CST 2020
     */
    int deleteByPrimaryKey(CategoryBrandKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbggenerated Wed Aug 26 13:00:16 CST 2020
     */
    int insert(CategoryBrandKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category_brand
     *
     * @mbggenerated Wed Aug 26 13:00:16 CST 2020
     */
    int insertSelective(CategoryBrandKey record);

    List<Category> selectList(Long bid);
}