package cn.itcast.mapper;

import com.leyou.pojo.Spu;
import com.leyou.pojo.SpuExample;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spu
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spu
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    int insert(Spu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spu
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    int insertSelective(Spu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spu
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    List<Spu> selectByExample(SpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spu
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    Spu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spu
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    int updateByPrimaryKeySelective(Spu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spu
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    int updateByPrimaryKey(Spu record);

    @Select("select * from tb_spu ORDER BY id desc LIMIT 1")
    Spu selectTop();
}