package com.leyou.pojo;

import lombok.Data;

import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
public class Spu implements Serializable {

    private Long id;
    private String title;
    private String subTitle;
    private Long cid1;
    private Long cid2;
    private Long cid3;
    private Long brandId;
    private Boolean saleable;
    private Boolean valid;
    private Date createTime;
    private Date lastUpdateTime;
    private static final long serialVersionUID = 1L;


    @Transient //查数据库时候不用
    private  String bname; // 品牌名称
    @Transient
    private  String cname; // 商品分类名称

    @Transient
    SpuDetail spuDetail;// 商品详情
    @Transient
    List<Sku> skus;// sku列表

    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }


    public String getTitle() {
        return title;
    }


    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }


    public String getSubTitle() {
        return subTitle;
    }


    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.cid1
     *
     * @return the value of tb_spu.cid1
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Long getCid1() {
        return cid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.cid1
     *
     * @param cid1 the value for tb_spu.cid1
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setCid1(Long cid1) {
        this.cid1 = cid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.cid2
     *
     * @return the value of tb_spu.cid2
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Long getCid2() {
        return this.cid2 =cid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.cid2
     *
     * @param cid2 the value for tb_spu.cid2
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setCid2(Long cid2) {
        this.cid2 = cid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.cid3
     *
     * @return the value of tb_spu.cid3
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Long getCid3() {
        return cid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.cid3
     *
     * @param cid3 the value for tb_spu.cid3
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setCid3(Long cid3) {
        this.cid3 = cid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.brand_id
     *
     * @return the value of tb_spu.brand_id
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.brand_id
     *
     * @param brandId the value for tb_spu.brand_id
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.saleable
     *
     * @return the value of tb_spu.saleable
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Boolean getSaleable() {
        return saleable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.saleable
     *
     * @param saleable the value for tb_spu.saleable
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setSaleable(Boolean saleable) {
        this.saleable = saleable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.valid
     *
     * @return the value of tb_spu.valid
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.valid
     *
     * @param valid the value for tb_spu.valid
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.create_time
     *
     * @return the value of tb_spu.create_time
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.create_time
     *
     * @param createTime the value for tb_spu.create_time
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_spu.last_update_time
     *
     * @return the value of tb_spu.last_update_time
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_spu.last_update_time
     *
     * @param lastUpdateTime the value for tb_spu.last_update_time
     *
     * @mbggenerated Fri Aug 28 22:45:07 CST 2020
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}